[project]
name = "time-locked-wallet"
description = "Enhanced time-locked wallet system with multi-vault support and improved security"
authors = ["Your Name <your.email@example.com>"]

[contracts.vault]
path = "contracts/vault.clar"

[contracts.multi-vault]
path = "contracts/multi-vault.clar"
